[package]
name = "astra_observer"
version = "0.0.1"
authors = ["Salim Largo <me@2ourc3.com>"]
edition = "2024"


[dependencies]
libc = "0.2.177"
rustix = { version = "1.1.2", features = ["fs", "mm", "shm"] }
